dataset_params:
  train_path: 'chest_xray/train'
  test_path: 'chest_xray/test'
  target_class: 'NORMAL'
  image_size: 240
  num_workers: 2

  csv_path: "F:/BraTS2020/BraTS20 Training Metadata.csv" #"BraTS20 Training Metadata.csv"
  data_root: "F:/BraTS2020/BraTS2020_training_data/content/data"
  
  # Filtering Thresholds
  min_slice: 40
  max_slice: 124
  tumor_threshold: 1400
  
  # Training Target ('significant_tumor' or 'no_tumor')
  target_class: "significant_tumor"
  
  # DataLoader params
  batch_size: 8
  shuffle_bool: true
  channel_index: 3


diffusion_params:
  timesteps: 1000
  beta_begin: 0.0001
  beta_end: 0.02

model_params:
  image_channels: 1
  image_size: 120
  down_channels: [64, 128, 256, 512]
  mid_channels: [512, 512, 256]
  down_sample: [True, True, False]
  time_emb_dim: 128
  num_down_layers: 2
  num_mid_layers: 2
  num_up_layers: 2
  num_heads: 4


train_params:
  output_folder: 'default'
  shuffle_bool: true
  alpha: 0.84
  num_epochs: 10
  samples: 16
  rows: 4
  learning_rate: 0.0001
  checkpoint_file: 'ddpm_wavelet.pth'
